Update printer-creality-ender3-s1-2022.cfg
Klipper3d/klipper pull request #5944
Opened 2022-12-17 10:59 UTC by fire1ce

Added precise location of [bed_screws] for ender s1

2022-12-31 02:02 UTC, KevinOConnor commented
@Fisheiyy - any thoughts on this?

-Kevin

2022-12-31 02:28 UTC, Fisheiyy commented
@fire1ce Is this necessary? I would like to keep the config as barebones as possible to reduce new-comer confusion, and the bed screws thing is confusing for me, because of the clock representation of rotations, so do you think a new user would understand it and be able to use this feature?

2022-12-31 13:56 UTC, fire1ce commented
@Fisheiyy I think u are looking at this from the wrong perspective. Let me clarify, Klipper firmware as a base line isn’t for the “noobies” also when i was first installing klipper i was looking for the most complete config there is. Which made me go looking for other ppl configs that i weren’t sure are even correct since the Official ones didn’t had some stuff. For the point of adding the Bed Screws position, Its a hardware part of this printer, not really something a user should change unless he modded the printers bed. At my point any Default Hardware configuration should be present at klipper initial config. Thats my opinion from my experience.

2022-12-31 14:00 UTC, fire1ce commented
Also i wanted to add that I've looks for those settings at probably more then 20 other people configs, there where all wrong. So i had to take the positions manually

2022-12-31 14:27 UTC, Sineos commented
Given that the location is correct and according to standard Ender 3 S1 then it definitively makes sense in my opinion.
Bed leveling is an important task and this makes it easier

2023-01-01 05:31 UTC, Fisheiyy requested changes

2023-01-01 05:31 UTC, Fisheiyy commented on config/printer-creality-ender3-s1-2021.cfg
> +# Ender-3-s1 bed
Remove this and this can be merged.

2023-01-02 15:19 UTC, KevinOConnor commented
Thanks.  The change looks fine to me.  However, commits need to have a signed-off-by line - https://www.klipper3d.org/CONTRIBUTING.html .

-Kevin

2023-01-02 20:05 UTC, fire1ce commented
> Thanks. The change looks fine to me. However, commits need to have a signed-off-by line - https://www.klipper3d.org/CONTRIBUTING.html .
> 
> -Kevin

Hey Kevein, thanks for pointing this out. 
I have edited the first comment with the relevant information.

2023-01-02 20:22 UTC, merged

2023-01-02 20:23 UTC, KevinOConnor commented
Thanks.

-Kevin

2023-02-10 11:09 UTC, Littlericket commented
@KevinOConnor @Fisheiyy 

How about having screws_tilt_adjust instead of bed_screws, since e3s1 is equipped with zprobe by default anyways.

```
[screws_tilt_adjust]
screw1: 50, 67
screw1_name: front left
screw2: 226, 67
screw2_name: front right
screw3: 226, 225
screw3_name: back right
screw4: 50, 225
screw4_name: back left
horizontal_move_z: 10.
speed: 50.
screw_thread: CW-M3
```