Initial commit for TronXY X5SA-2E printer config.
Klipper3d/klipper pull request #5987
Opened 2023-01-14 10:57 UTC by patchMonkey156

as the [shared_heater] tag is deprecated, it was avoided in favor the T0 and T1 macros that are already necessary. 

This config should be considered "initial" in that the user can rely on the pinouts, but needs to configure most of the other details themselves using the printer and SuperSlicer or some equivalent.

Pinouts for your tronXY printer on this motherboard can be mined from their GitHub project for the TronXY Marlin firmware.

This printer's pinouts were mined from
https://github.com/tronxy3d/F4xx-SIM480x320/blob/firmware/Marlin/src/pins/stm32f4/pins_TRONXY_F446.h

The File for some Single extrusion variants of the F446 boards: https://github.com/tronxy3d/F4xx-SIM240x320/blob/firmware/Marlin/src/pins/stm32f4/pins_TRONXY_F446.h The file for Legacy F103 Boards:
https://github.com/tronxy3d/STM32F103-PIC480x320/blob/firmware/Marlin/src/pins/stm32f4/pins_TRONXY_F446.h

2023-01-14 20:22 UTC, JamesH1978 commented
Hi,

thank you for submitting your config.

Please can you make sure you have followed the guidelines in https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md and https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md paying particualr atetntion to the signed off by line and the printer regression test case that you need to add to.

Thanks
James

2023-01-24 17:15 UTC, JamesH1978 requested changes
As per my last comment, i have noted a few changes.

You need to read https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md especially the signed off by line

You also need to refer to https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md especially point 4 and add the regression tests

I have also made a few initial comments to the code.

Thanks
James

2023-01-24 17:29 UTC, patchMonkey156 commented on printer-tronxy-x5sa-2e-2022.cfg
> +endstop_pin: probe:z_virtual_endstop
Thank you, that makes this even nicer! I'm still figuring out how to resolve all of this on github itself.

2023-01-24 17:30 UTC, patchMonkey156 commented on printer-tronxy-x5sa-2e-2022.cfg
> +max_extrude_only_distance: 350
I was unaware of doing such. Thank you for the assistance.

2023-01-24 17:39 UTC, patchMonkey156 commented
> As per my last comment, i have noted a few changes.
> 
> You need to read https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md especially the signed off by line
> 
> You also need to refer to https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md especially point 4 and add the regression tests
> 
> I have also made a few initial comments to the code.
> 
> Thanks James
I believe that is the format for the signed-off-by line? Thank you for the guidance.

The regression tests? Will take a bit longer as I read the documentation on how to address this. Thank you for your assistance!

2023-02-22 12:02 UTC, closed without merging