config: Example config file for Creality CR5 Pro HT
Klipper3d/klipper pull request #6089
Opened 2023-03-05 02:10 UTC by bakerbrandond

2023-03-05 02:16 UTC, bakerbrandond commented
I'll do one more verification tomorrow but otherwise I'm looking forward to feedback.

2023-03-07 00:28 UTC, bakerbrandond commented
Ok, I've squashed down my fixups.  I've reviewed the machine description [here](https://www.creality.com/products/creality-cr-5-pro-h-3d-printer) and have ensured the x,y, and z min/max are in safe ranges and verified against the actual machine (needed to shave a bit off of y to be safe).  This is now ready for widespread deployment.

2023-03-07 00:30 UTC, bakerbrandond commented
Do note that this PR will result in a printer without functional touchscreen.  How do we handle this?  I see [this](https://klipper.discourse.group/t/dwin-t5uid1-touchscreen-support/2411) outstanding discussion.

2023-03-08 10:07 UTC, JamesH1978 commented
Thankyou for submitting a PR, please can you refer to https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md paying particular attention to the signed-off-by line.

Also please refer to https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md and make sure you follow the guidelines including adding the regression tests in printers.test as outlined to point 4.

Thanks
James

2023-03-10 01:19 UTC, bakerbrandond commented
@JamesH1978 ready for review?

2023-03-10 16:34 UTC, JamesH1978 requested changes
Looks fine to me apart from the comment I made about the stowing of the pin.

Can you also confirm that this printer has endstops at axis minimum, and not axis maximum. ie are endstops back right or front left?

Thanks
James

2023-03-10 17:42 UTC, bakerbrandond commented on config/printer-creality-cr5pro-ht-2022.cfg
> +stow_on_each_sample: False
Updated.  Endstops are confirmed front left.

2023-03-10 17:53 UTC, bakerbrandond commented on config/printer-creality-cr5pro-ht-2022.cfg
> +stow_on_each_sample: False
made sure to add Signed-off-by to latest commit.  would you prefer I squash?

2023-03-10 18:14 UTC, JamesH1978 approved these changes
Looks fine to me

Thanks
James

2023-03-11 16:30 UTC, merged

2023-03-11 16:30 UTC, KevinOConnor commented
Thanks.

-Kevin

2023-11-21 10:23 UTC, hlinden commented
@bakerbrandond Hey, just a quick thank you for this commit. This turned my 1k€ paperweight into an actually usable printer, but I'd never have managed to create a klipper config from scratch.

2023-11-21 15:46 UTC, bakerbrandond commented
> @bakerbrandond Hey, just a quick thank you for this commit. This turned my 1k€ paperweight into an actually usable printer, but I'd never have managed to create a klipper config from scratch.

Hey bro! Thanks for taking the time out to share appreciation. Glad I could help. I was able to score one on Craigslist and when I saw there was no config I couldn't stand idly by!

Please let me know how she runs and if you have any issues. As far as I know you and I are the only ones using this printer with Klipper.

Last note... Try OrcaSlicer their built in printer tuning wizards and wiki is great!

2024-01-08 02:42 UTC, TheBinaryLoop commented
@bakerbrandond I've got this setup running for a few months now and it works flawlessly. I couldn't get my printer to work with stock settings no matter what I tried. Now I can just press print, go about my day and be sure that it will print correctly (perfect first layer and so on).

2024-01-08 11:55 UTC, hlinden commented
@bakerbrandond sorry - I've kept radio silence until now because I still have some issues - make no mistake, Klipper and your config absolutely fixed the printer as far as possible in software. I do have trouble with some filament gliding better or worse in the bowden tube, depending on the bend radius. This means, there is not really a single good value for all things related to handling the filament, when I'm good for printing things on the front left corner I'll get massive underextrusion in the rear right.

That's not really a software problem - while it could somewhat be fixed in software somewhat, probably _(although I don't think Klipper supports position dependend lookup tables for config values)_ I decided to mount a direct extruder, because, mechanical problems should be fixed mechanically first, imho.

The adapter is printed in ASA and lying here, an Orbiter extruder is mounted on top, an adxl345 is stuck to it with some cat 6 soldered neatly on and that's about where the whole thing lost steam mid-december and has been sitting on my workbench since then.

I'll give feedback when that modification is running!

2024-01-08 17:16 UTC, bakerbrandond commented
> @bakerbrandond I've got this setup running for a few months now and it works flawlessly. I couldn't get my printer to work with stock settings no matter what I tried. Now I can just press print, go about my day and be sure that it will print correctly (perfect first layer and so on).

So happy to contribute to this community. Happy New Year. Happy Printing!

2024-01-08 17:18 UTC, bakerbrandond commented
> @bakerbrandond sorry - I've kept radio silence until now because I still have some issues - make no mistake, Klipper and your config absolutely fixed the printer as far as possible in software. I think I had to adjust the Z-Position of the BLtouch but everything else was really fine out of the box. 
> 
> The rest of my trouble is of mechanical nature: I do have trouble with some filament gliding better or worse in the bowden tube, depending on the bend radius. This means, there is not really a single good value for all things related to handling the filament, when I'm good for printing things on the front left corner I'll get massive underextrusion in the rear right.
> 
> That's not really a software problem - while it could somewhat be fixed in software somewhat, probably _(although I don't think Klipper supports position dependend lookup tables for config values)_ I decided to mount a direct extruder, because, mechanical problems should be fixed mechanically first, imho.
> 
> The adapter is printed in ASA and lying here, an Orbiter extruder is mounted on top, an adxl345 is stuck to it with some cat 6 soldered neatly on and that's about where the whole thing lost steam mid-december and has been sitting on my workbench since then.
> 
> I'll give feedback when that modification is running!

Hmmm that sounds like an interesting solution. I'm wondering if swapping out the bowden tube for a Capricorn would have helped at all.

2024-03-28 08:55 UTC, zhujiang0086 commented
@bakerbrandond Thank you very much for providing this configuration file. Could you please also share the parameter settings for menuconfig? I am a bit worried about whether I can successfully update the firmware or not.

2024-03-28 09:26 UTC, JamesH1978 commented
the setting are at the top of the file ```# This file contains common pin mappings for the Creality CR5 Pro HT.
# The mainboard is a Creality 3D v2.5.1 (8-bit mainboard with
# ATMega2560). To use this config, the firmware should be compiled for
# the AVR atmega2560.```

![image](https://github.com/Klipper3d/klipper/assets/87171443/67422be6-e349-436c-9a33-f86c04e4306f)

2024-03-29 02:25 UTC, zhujiang0086 commented
@JamesH1978 Thank you! I will try this.

2024-08-08 14:03 UTC, DragonSlayerSE commented
Did someone document all the pins on the creality 3d v2.5.1 motherboard? i am trying to run klipper on CR-3040 Pro that has the same mb but not the same wiering
![cr3040_pro_mb](https://github.com/user-attachments/assets/a46eb7cc-4888-49f2-a250-d80b50615881)

2024-12-27 00:29 UTC, bakerbrandond commented
> Did someone document all the pins on the creality 3d v2.5.1 motherboard? i am trying to run klipper on CR-3040 Pro that has the same mb but not the same wiering ![cr3040_pro_mb](https://private-user-images.githubusercontent.com/13795847/356253744-a46eb7cc-4888-49f2-a250-d80b50615881.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNTk2MzksIm5iZiI6MTczNTI1OTMzOSwicGF0aCI6Ii8xMzc5NTg0Ny8zNTYyNTM3NDQtYTQ2ZWI3Y2MtNDg4OC00OWYyLWEyNTAtZDgwYjUwNjE1ODgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAwMjg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YzRjMGE1YTA1ZDBhMGJiN2M3MTFiM2IzMzM0Y2YxNzE4NDcxMTgxYzYxOWU5MTJkZDY2OGIzNzQ2ZGJjZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._FB_0FMDJyz1QqmOcMmLZuG7ZRBH_SOEBjjsY_9gf3g)

what exactly is your issue?