config: Add Ratrig V-Minion
Klipper3d/klipper pull request #6120
Opened 2023-03-16 04:26 UTC by bbro44

This adds support for the stock configuration of the V-Minion printer from Ratrig, based on the Octopus v1.1 (STM32F446)

2023-03-16 09:15 UTC, JamesH1978 requested changes
Thank you for submitting this config, I have made some comments.

Thanks,
James

2023-03-16 09:15 UTC, JamesH1978 commented on config/printer-ratrig-v-minion-2021.cfg
> +# communication.
Please state that this F446 board needs a 12MHZ crystal(stock crystal setting causes many timing issues

Thanks
James

2023-03-16 09:15 UTC, JamesH1978 commented on config/printer-ratrig-v-minion-2021.cfg
> +# with an Octopus Pro v1.1 board.
Please state that this is for the "full kit" version, as configs should only describe stock hardware that an end user would receive, we do not accept DIY printers due to the massive amount of variation that can be involved. If this config describes one of those DIY variants then we would be inclined not to accept this addition.

You may also want to state that this config will not have the full out of the box functionality of the stock ratos version of klipper.

Thanks
James

2023-03-29 10:58 UTC, JamesH1978 approved these changes
Looks fine to me.

Thanks,
James

2023-03-29 13:53 UTC, merged

2023-03-29 13:54 UTC, KevinOConnor commented
Thanks.

-Kevin

2023-03-31 13:45 UTC, dewi-ny-je commented
20000 as standard acceleration? from the videos I saw online, that can be achieved only AFTER input shaping. The standard config file should be less extreme. 
For example, the Voron is set to 3000 as standard, which is a good starting point if no tuning is performed.

Can the V-minion use such high acceleration without input shaping?

2023-03-31 17:39 UTC, bbro44 commented
Good point, I always forget that its default instead of max. I can update that once I get back from my trip. Thanks!