adding 64k bootloader offset to the stm32f407 mcu
Klipper3d/klipper pull request #6121
Opened 2023-03-16 12:48 UTC by raptordemon

adding 64k bootloader offset to the stm32f407 mcu this allows for it to be built for the Mingda Magician X printer.

2023-03-16 14:00 UTC, raptordemon commented
added 64k bootloader to the stm32f407 and the initial config for the mingda magician x series of printers. they have a custom bootloader which is 64k

2023-03-16 20:58 UTC, raptordemon commented
adding 64k bootloader offset to the stm32f407 mcu this allows for it to be built for the Mingda Magician X printer and the example cfg for the magician x

2023-03-17 17:58 UTC, raptordemon commented
module: adding support for the mingda magician x printer. it needs a 64k bootloader offset on the stm32f407 mcu

changed the kconifg in stm32 to allow for a 64k bootloader option for the mingda magician x as they use a custom bootloader for some reason.

i have also added a config file for this printer to help new users get started.

Signed-off-by: David Ingram raptordemon@gmail.com

2023-03-17 18:05 UTC, raptordemon commented
thanks James is that what i needed to do?

2023-03-28 02:26 UTC, raptordemon commented
Ok I will fix these too, thanks

2023-04-14 14:16 UTC, raptordemon commented
Hello i have fixed the requested changes. pls let me knw if i have missed anything

thanks
Raptor

2023-04-14 14:33 UTC, JamesH1978 requested changes
I have made some comments

You also need to add printer regression tests as per point 4 https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md

Thanks
James

2023-04-14 14:33 UTC, JamesH1978 commented on config/printer-Mingda-Magician-X-2023.cfg
> +[include mainsail.cfg]
please do not include cfg files that an end user may not have or need

Thanks
James

2023-04-14 14:33 UTC, JamesH1978 commented on config/printer-Mingda-Magician-X-2023.cfg
> +[neopixel my_neopixel]
Are these stock attached to the printer?

Thanks
James

2023-04-14 14:33 UTC, JamesH1978 commented on config/printer-Mingda-Magician-X-2023.cfg
> +[filament_switch_sensor toolhead_runout]
Is this a stock feature?

Thanks
James

2023-04-29 00:06 UTC, closed without merging