Add AHT10 temperature sensor doc section in Config_Reference.md (followup #6138)
Klipper3d/klipper pull request #6167
Opened 2023-04-13 13:31 UTC by scottmudge

Added relevant documentation in `Config_Reference.md` for AHT10 temperature sensor. This is a follow-up to #6138 .

2023-04-14 00:41 UTC, thijstriemstra requested changes

2023-04-14 00:41 UTC, thijstriemstra commented on docs/Config_Reference.md
> +heater beds, but rather for monitoring ambient temperature (C) and
C -> °C

2023-04-14 00:41 UTC, thijstriemstra commented on docs/Config_Reference.md
> +[sample-macros.cfg](../config/sample-macros.cfg) for a gcode_macro
gcode_macro -> `gcode_macro`

2023-04-15 23:17 UTC, merged

2023-04-15 23:19 UTC, KevinOConnor commented
Thanks.  I committed this change.

Cheers,
-Kevin