Add MKS Monster 8 generic config
Klipper3d/klipper pull request #6336
Opened 2023-09-08 17:25 UTC by Bomberski

Adding MKS Monster 8 generic configuration

Signed-off-by: Allen Cox <Bomberski420@gmail.com>

2023-09-08 17:55 UTC, JamesH1978 requested changes
Looks fine to me, just the = to change, as remarked, plus the homing_speeds.

Thanks
James

2023-09-08 17:55 UTC, JamesH1978 commented on config/generic-mks-monster8.cfg
> +control = pid
Please change to : instead of =

Thanks
James

2023-09-08 17:55 UTC, JamesH1978 commented on config/generic-mks-monster8.cfg
> +homing_speed: 100
Please leave homing_speed at default, some printers may not take kindly to being asked to home at twice default.

Thanks
James

2023-09-08 17:55 UTC, JamesH1978 commented on config/generic-mks-monster8.cfg
> +homing_speed: 100
Same as above

2023-09-08 17:55 UTC, JamesH1978 commented on config/generic-mks-monster8.cfg
> +homing_speed: 25
Same as above

2023-09-08 19:28 UTC, Bomberski commented
I believe that's default sppeds

2023-09-08 20:28 UTC, JamesH1978 commented
`#homing_speed: 5.0
#   Maximum velocity (in mm/s) of the stepper when homing. The default
#   is 5mm/s.` :)

2023-09-08 20:31 UTC, Bomberski commented
> ```
> #   Maximum velocity (in mm/s) of the stepper when homing. The default
> #   is 5mm/s.``` :)
> ```

I will swap from 50 to 5, thank you

2023-09-08 20:33 UTC, JamesH1978 commented
and i meant change = to : on all those option in heater_bed, and i edited my reply to say 50 is fine, it used in most example.

Thanks
James

2023-09-08 23:13 UTC, JamesH1978 approved these changes
Looks good to me

Thanks
James

2023-09-10 17:55 UTC, merged

2023-09-10 17:55 UTC, KevinOConnor commented
Thanks.

-Kevin