Update Kconfig
Klipper3d/klipper pull request #6534
Opened 2024-03-18 21:31 UTC by TheFeralEngineer

add 48KiB bootloader option to STM32F401 for Artillery Sidewinder X3 boards

2024-03-23 11:46 UTC, JamesH1978 commented
Thank you for submitting a PR. You will need to fix your code remove the trading spaces as per the checks error, And you will need to also need to do the regression tests and sign off your PR. Point 4 in the guidelines in https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md and point 3 in What to expect in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md

Thanks
James

2024-03-25 22:18 UTC, TheFeralEngineer commented on src/stm32/Kconfig
> +        bool "48KiB bootloader" if MACH_STM32F4x5 || MACH_STM32F401
add stm32f401 to 48KiB for Artillery Sidewinder X3

2024-03-25 22:20 UTC, TheFeralEngineer reviewed
added additional information

2024-03-25 22:27 UTC, TheFeralEngineer reviewed
removed whitespaces

2024-03-25 22:45 UTC, TheFeralEngineer commented
> Thank you for submitting a PR. You will need to fix your code remove the trading spaces as per the checks error, And you will need to also need to do the regression tests and sign off your PR. Point 4 in the guidelines in https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md and point 3 in What to expect in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md
> 
> Thanks James

I'm completely new to this PR stuff, so bear with me...

2024-03-25 22:50 UTC, TheFeralEngineer reviewed
basic .cfg

2024-03-25 22:53 UTC, TheFeralEngineer reviewed
removed another whitespace

2024-03-25 22:56 UTC, TheFeralEngineer reviewed
removed uppercase letters in config name

2024-03-26 14:18 UTC, JamesH1978 commented
Thank you for the changes you have made so far but you still need to provide a [test/klippy/printers.test](https://github.com/Klipper3d/klipper/blob/master/test/klippy/printers.test) file with the entry added for your new file, so it can pass regression tests as per the doc i linked.

Thanks
James

2024-03-26 14:28 UTC, Sineos requested changes
Thanks for your contribution.
Some comments added and apparently a signed-off line is also missing

2024-03-26 14:28 UTC, Sineos commented on config/printer-artillery-sidewinder-x3-plus-2024.cfg
> +#samples_tolerance_retries:
remove or add values deviating from the defaults where necessary.

2024-03-26 14:28 UTC, Sineos commented on config/printer-artillery-sidewinder-x3-plus-2024.cfg
> +#   By default no faulty regions are set.
see above

2024-03-26 20:09 UTC, TheFeralEngineer commented on config/printer-artillery-sidewinder-x3-plus-2024.cfg
> +#   By default no faulty regions are set.
removed

2024-03-27 03:08 UTC, TheFeralEngineer commented
/src/stm32/Kconfig: Added MACH_STM32F401 to 48KiB bootloader for Artillery Sidewinder x3 printers
/config: Added printer.cfg

all I'm trying to do is upload a printer.cfg and a small change to Kconfig. I haven't changed anything else in the source code and all of the tests I've ran have passed. I'm kinda at a loss here and don't know what else to do. 


Signed-off-by: Phil Timpson<theferalengineer@gmail.com>

2024-03-27 10:26 UTC, Sineos commented
Thanks for your changes.
What is missing is adding your new config to the regression testing. See https://github.com/Klipper3d/klipper/pull/6119/files for an example.

I apparently missed one thing during my review:

```
[force_move]
enable_force_move: True
```

Please do not activate such functions in the default config unless there is a compelling reason to do so.

2024-03-27 20:04 UTC, TheFeralEngineer commented
> Thanks for your changes. What is missing is adding your new config to the regression testing. See https://github.com/Klipper3d/klipper/pull/6119/files for an example.
> 
> I apparently missed one thing during my review:
> 
> ```
> [force_move]
> enable_force_move: True
> ```
> 
> Please do not activate such functions in the default config unless there is a compelling reason to do so.

30th time's a charm 🤞🤞

2024-03-27 20:20 UTC, TheFeralEngineer commented
now it keeps failing. I'm no good at this 😭

2024-03-27 20:22 UTC, TheFeralEngineer reviewed
spelling error

2024-03-28 00:30 UTC, JamesH1978 requested changes
Sorry to give you one more set of adjustments :) but apart from my comments it all looks good to me as well.

and good work!

Thanks
James

2024-03-28 00:30 UTC, JamesH1978 commented on config/printer-artillery-sidewinder-x3-plus-2024.cfg
> +control = pid
Please can you normalise these to : instead of equals

Thanks
James

2024-03-28 00:30 UTC, JamesH1978 commented on config/printer-artillery-sidewinder-x3-plus-2024.cfg
> +control = pid
Same as above

2024-03-28 00:30 UTC, JamesH1978 commented on config/printer-artillery-sidewinder-x3-plus-2024.cfg
> +z_offset = 2.350
Same as above

2024-03-28 00:54 UTC, TheFeralEngineer commented
oh, that's easy. I copied them directly from the bottom of my config (i guess the save_config puts them that way). I was starting to get a little distraught at all of the build failures before, but I think I've got it figured out now 🙂. I'll take care of it right away.
________________________________
From: JamesH1978 ***@***.***>
Sent: Wednesday, March 27, 2024 8:30 PM
To: Klipper3d/klipper ***@***.***>
Cc: TheFeralEngineer ***@***.***>; Author ***@***.***>
Subject: Re: [Klipper3d/klipper] Update Kconfig (PR #6534)


@JamesH1978 requested changes on this pull request.

Sorry to give you one more set of adjustments :) but apart from my comments it all looks good to me as well.

and good work!

Thanks
James

________________________________

In config/printer-artillery-sidewinder-x3-plus-2024.cfg<https://github.com/Klipper3d/klipper/pull/6534#discussion_r1542178413>:

> +dir_pin: !PC10
+enable_pin: !PC12
+microsteps: 64
+nozzle_diameter: 0.400
+filament_diameter: 1.750
+heater_pin: PA6
+sensor_type: EPCOS 100K B57560G104F #Generic 3950
+sensor_pin: PC5
+min_extrude_temp: 170
+min_temp: 0
+max_temp: 300
+# Calibrate E-Steps https://www.klipper3d.org/Rotation_Distance.html#calibrating-rotation_distance-on-extruders
+rotation_distance: 17.75
+# Calibrate PID: https://www.klipper3d.org/Config_checks.html#calibrate-pid-settings
+#  - Example: PID_CALIBRATE HEATER=extruder TARGET=200
+control = pid


Please can you normalise these to : instead of equals

Thanks
James

________________________________

In config/printer-artillery-sidewinder-x3-plus-2024.cfg<https://github.com/Klipper3d/klipper/pull/6534#discussion_r1542178606>:

> +#  - Example: PID_CALIBRATE HEATER=extruder TARGET=200
+control = pid
+pid_kp = 30.356
+pid_ki = 1.857
+pid_kd = 124.081
+# Calibrate PA: https://www.klipper3d.org/Pressure_Advance.html
+
+[heater_bed]
+heater_pin: PA7
+sensor_type: EPCOS 100K B57560G104F
+sensor_pin: PC0
+max_temp: 100
+min_temp: 0
+# Calibrate PID: https://www.klipper3d.org/Config_checks.html#calibrate-pid-settings
+#  - Example: PID_CALIBRATE HEATER=heater_bed TARGET=60
+control = pid


Same as above

________________________________

In config/printer-artillery-sidewinder-x3-plus-2024.cfg<https://github.com/Klipper3d/klipper/pull/6534#discussion_r1542178695>:

> +off_below: 0.19
+max_speed: 1.0
+min_speed: 0.0
+control: watermark
+
+[filament_switch_sensor filament_sensor]
+pause_on_runout: true
+switch_pin: PC1
+
+[probe]
+pin: PC14
+x_offset:45.2
+y_offset:11.6
+speed:5
+lift_speed:15
+z_offset = 2.350


Same as above

—
Reply to this email directly, view it on GitHub<https://github.com/Klipper3d/klipper/pull/6534#pullrequestreview-1964964249>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARUZ2LMXZWVEC5NKLGQSUNDY2NJDBAVCNFSM6AAAAABE4MHAX6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNRUHE3DIMRUHE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-28 06:29 UTC, Sineos approved these changes
Thanks for your work. Appreciated. LGTM with a little nit.

2024-03-28 06:29 UTC, Sineos commented on test/klippy/printers.test
>  CONFIG ../../config/printer-creality-ender5-s1-2023.cfg
Little nitpick: Please keep these lists sorted

```
CONFIG ../../config/generic-fysetc-cheetah-v2.0.cfg
CONFIG ../../config/printer-artillery-sidewinder-x2-2022.cfg
CONFIG ../../config/printer-artillery-sidewinder-x3-plus-2024.cfg
CONFIG ../../config/printer-creality-ender5-s1-2023.cfg
CONFIG ../../config/printer-elegoo-neptune3-pro-2023.cfg
```

2024-03-28 08:18 UTC, TheFeralEngineer commented
Yeah, sorry. Wasn't sure where to put it. I originally had it at the bottom
of the dictionary, but the example that was sent to me showed the most
recent addition at the top, that's why I put it there 🥴

Phil T.
The Feral Engineer

www.theferalengineer.com

Catnip contributions 🐱🐱
https://paypal.me/timpsonmusicllc


On Thu, Mar 28, 2024, 2:29 AM Sineos ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Thanks for your work. Appreciated. LGTM with a little nit.
> ------------------------------
>
> In test/klippy/printers.test
> <https://github.com/Klipper3d/klipper/pull/6534#discussion_r1542379668>:
>
> > +CONFIG ../../config/printer-artillery-sidewinder-x3-plus-2024.cfg
>  CONFIG ../../config/generic-fysetc-cheetah-v2.0.cfg
>  CONFIG ../../config/printer-artillery-sidewinder-x2-2022.cfg
>  CONFIG ../../config/printer-creality-ender5-s1-2023.cfg
>
> Little nitpick: Please keep these lists sorted
>
> CONFIG ../../config/generic-fysetc-cheetah-v2.0.cfg
> CONFIG ../../config/printer-artillery-sidewinder-x2-2022.cfg
> CONFIG ../../config/printer-artillery-sidewinder-x3-plus-2024.cfg
> CONFIG ../../config/printer-creality-ender5-s1-2023.cfg
> CONFIG ../../config/printer-elegoo-neptune3-pro-2023.cfg
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Klipper3d/klipper/pull/6534#pullrequestreview-1965266877>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARUZ2LOERGUIWFZAQZO5FFLY2OTDPAVCNFSM6AAAAABE4MHAX6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNRVGI3DMOBXG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-29 03:19 UTC, TheFeralEngineer commented on test/klippy/printers.test
>  CONFIG ../../config/printer-creality-ender5-s1-2023.cfg
fixed 😋

2024-04-03 01:51 UTC, KevinOConnor commented
Thanks.  So is this PR now ready to merge?

-Kevin

2024-04-03 01:54 UTC, TheFeralEngineer commented
it should be, yes. It passed all of the tests, I signed off on it, Sineos approved it but mentioned I should reorder the printers.test file, so I did. Other than that, everything should be all systems go.
________________________________
From: KevinOConnor ***@***.***>
Sent: Tuesday, April 2, 2024 9:51 PM
To: Klipper3d/klipper ***@***.***>
Cc: TheFeralEngineer ***@***.***>; Author ***@***.***>
Subject: Re: [Klipper3d/klipper] Update Kconfig (PR #6534)


Thanks. So is this PR now ready to merge?

-Kevin

—
Reply to this email directly, view it on GitHub<https://github.com/Klipper3d/klipper/pull/6534#issuecomment-2033394700>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARUZ2LMXOATW6AZNQRO6RB3Y3NODZAVCNFSM6AAAAABE4MHAX6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZTGM4TINZQGA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-12 16:27 UTC, merged

2024-04-12 16:27 UTC, KevinOConnor commented
Thanks.

-Kevin